// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGB-SlaKL_fEPgOo8V4HOMZazLZbv8HFA',
    appId: '1:481936674753:web:a3adcbe72a345798b5e940',
    messagingSenderId: '481936674753',
    projectId: 'grand-entertainment-26a61',
    authDomain: 'grand-entertainment-26a61.firebaseapp.com',
    storageBucket: 'grand-entertainment-26a61.appspot.com',
    measurementId: 'G-FH4KG132XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtn0PDWGaGzexM9u6vQqZu6yFUXREauuI',
    appId: '1:481936674753:android:5359b7fcbbbcd614b5e940',
    messagingSenderId: '481936674753',
    projectId: 'grand-entertainment-26a61',
    storageBucket: 'grand-entertainment-26a61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaldKFqyS5Pz5gKcD94pJJpICX9Sr9n8A',
    appId: '1:481936674753:ios:79e3b51d33b2a1e8b5e940',
    messagingSenderId: '481936674753',
    projectId: 'grand-entertainment-26a61',
    storageBucket: 'grand-entertainment-26a61.appspot.com',
    iosClientId: '481936674753-8d334g8nle140i7cbka1qbsfhk3da38b.apps.googleusercontent.com',
    iosBundleId: 'com.example.grandEntertainment',
  );
}
